FROM node:18-alpine

WORKDIR /app

# Copiamos package.json e instalamos dependencias
COPY package.json ./
RUN npm install

# Copiamos el resto del codigo
COPY . .

# Exponemos el puerto
EXPOSE 3000

# Usamos nodemon para que si cambias codigo, se reinicie solo
RUN npm install -g nodemon
CMD ["nodemon", "src/index.js"]