/**
 * @file projectController.js
 * @description
 * Handles incoming HTTP requests for research projects.
 * Enforces strict Data Isolation and Ownership Security for updates and deletions.
 */
const ProjectModel = require('../models/projectModel');
const AuditLogModel = require('../models/auditLogModel');

/**
 * Extracts integer IDs from a mixed array or JSON string of authors.
 *
 * @param {Array|string} authorsInput - The authors data from the request body.
 * @returns {Array<number>} An array of valid, clean author integer IDs.
 * @throws {Error} Safely catches parsing errors and logs a warning.
 */
const extractAuthorIds = (authorsInput) => {
  if (!authorsInput) return [];
  
  let authorsArray = authorsInput;
  
  if (typeof authorsInput === 'string') {
    try {
      authorsArray = JSON.parse(authorsInput);
    } catch (error) {
      console.warn('[WARN] Failed to parse authors string from FormData:', error.message);
      return [];
    }
  }

  if (!Array.isArray(authorsArray)) return [];
  
  return authorsArray.map(author => {
    if (typeof author === 'string' && author.startsWith('{')) {
      try { 
        return JSON.parse(author).id; 
      } catch (e) { 
        console.warn('[WARN] Failed to parse individual author object:', e.message);
        return null; 
      }
    }
    if (typeof author === 'object' && author !== null) {
      return author.id;
    }
    return parseInt(author, 10);
  }).filter(id => id !== null && !isNaN(id));
};

/**
 * Validates and extracts file buffers and mimetypes from the request.
 * Enforces file size limits (2MB for images, 5MB for PDFs).
 *
 * @param {Object} files - The req.files object generated by multer.
 * @returns {Object} An object containing extractedFiles and a possible error message.
 * @throws {Error} No explicit errors thrown; handles validation gracefully.
 */
const processProjectFiles = (files) => {
  const result = { extractedFiles: {}, error: null };
  if (!files) return result;

  if (files['image'] && files['image'][0]) {
    const imageFile = files['image'][0];
    if (imageFile.size > 2 * 1024 * 1024) {
      console.warn('[WARN] Image file exceeds 2MB limit');
      result.error = 'La imagen supera el límite máximo de 2MB.';
      return result;
    }
    result.extractedFiles.image_data = imageFile.buffer;
    result.extractedFiles.image_mimetype = imageFile.mimetype;
  }

  if (files['pdf'] && files['pdf'][0]) {
    const pdfFile = files['pdf'][0];
    if (pdfFile.size > 5 * 1024 * 1024) {
      console.warn('[WARN] PDF file exceeds 5MB limit');
      result.error = 'El documento supera el límite máximo de 5MB.';
      return result;
    }
    result.extractedFiles.pdf_data = pdfFile.buffer;
    result.extractedFiles.pdf_mimetype = pdfFile.mimetype;
  }

  return result;
};

/**
 * Retrieves research projects for the public website.
 *
 * @param {Object} req - The HTTP request object.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON response containing the list of all projects.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const getAllProjects = async (req, res) => {
  try {
    const projectsList = await ProjectModel.getAll();
    return res.status(200).json(projectsList);
  } catch (error) {
    console.error('[ERROR] Controller failed to fetch public projects:', error);
    return res.status(500).json({ message: 'Error interno al obtener las investigaciones.' });
  }
};

/**
 * Retrieves a specific research project by its ID.
 *
 * @param {Object} req - The HTTP request object containing params.id.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON response containing the project data.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const getProjectById = async (req, res) => {
  const { id } = req.params;
  try {
    const project = await ProjectModel.getById(id);
    if (!project) return res.status(404).json({ message: 'Proyecto no encontrado.' });
    return res.status(200).json(project);
  } catch (error) {
    console.error(`[ERROR] Failed to fetch project ${id}:`, error);
    return res.status(500).json({ message: 'Error interno al obtener el proyecto.' });
  }
};

/**
 * Creates a new research project, handling multipart/form-data images and PDFs.
 *
 * @param {Object} req - The HTTP request object containing body and files.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON response confirming creation.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const createProject = async (req, res) => {
  const { authors, ...projectData } = req.body;

  if (!projectData.title || !projectData.category_id) {
    return res.status(400).json({ message: 'El título y la categoría son obligatorios.' });
  }

  const { extractedFiles, error: fileError } = processProjectFiles(req.files);
  if (fileError) return res.status(400).json({ message: fileError });

  const cleanAuthorIds = extractAuthorIds(authors);
  const finalProjectData = { ...projectData, ...extractedFiles };

  try {
    const newProject = await ProjectModel.create(finalProjectData, cleanAuthorIds);

    if (req.user && req.user.id) {
      await AuditLogModel.logAction(req.user.id, 'CREATE', 'projects', newProject.id, { title: newProject.title });
    }

    return res.status(201).json(newProject);
  } catch (error) {
    console.error('[ERROR] Controller failed to create project:', error);
    return res.status(500).json({ message: 'Error interno al crear la investigación.' });
  }
};

/**
 * Updates an existing research project. Enforces ownership rules.
 *
 * @param {Object} req - The HTTP request object containing params.id, body, and files.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON response confirming update.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const updateProject = async (req, res) => {
  const { id } = req.params;
  const { authors, ...projectData } = req.body;

  if (!projectData.title) {
    return res.status(400).json({ message: 'El título de la investigación es obligatorio.' });
  }

  try {
    const existingProject = await ProjectModel.getById(id);
    if (!existingProject) return res.status(404).json({ message: 'La investigación solicitada no existe.' });

    const role = req.user ? req.user.role : 'guest';
    const userId = req.user ? req.user.id : null;

    if (role !== 'admin') {
      const currentAuthorIds = extractAuthorIds(existingProject.authors);
      if (!currentAuthorIds.includes(userId)) {
        return res.status(403).json({ message: 'Acceso denegado: Solo puedes editar investigaciones propias.' });
      }
    }

    const { extractedFiles, error: fileError } = processProjectFiles(req.files);
    if (fileError) return res.status(400).json({ message: fileError });

    const cleanAuthorIds = extractAuthorIds(authors);
    const finalProjectData = { ...projectData, ...extractedFiles };

    const updatedProject = await ProjectModel.update(id, finalProjectData, cleanAuthorIds);

    if (req.user && req.user.id) {
      await AuditLogModel.logAction(req.user.id, 'UPDATE', 'projects', id, { title: updatedProject.title });
    }

    return res.status(200).json(updatedProject);
  } catch (error) {
    console.error(`[ERROR] Controller failed to update project ID ${id}:`, error);
    return res.status(500).json({ message: 'Error interno al actualizar la investigación.' });
  }
};

/**
 * Deletes a research project. Enforces ownership rules.
 *
 * @param {Object} req - The HTTP request object.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON response confirming deletion.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const deleteProject = async (req, res) => {
  const { id } = req.params;

  try {
    const existingProject = await ProjectModel.getById(id);
    if (!existingProject) return res.status(404).json({ message: 'La investigación solicitada no existe o ya fue eliminada.' });

    const role = req.user ? req.user.role : 'guest';
    const userId = req.user ? req.user.id : null;

    if (role !== 'admin') {
      const currentAuthorIds = extractAuthorIds(existingProject.authors);
      if (!currentAuthorIds.includes(userId)) {
        return res.status(403).json({ message: 'Acceso denegado: No tienes permiso para eliminar esta investigación.' });
      }
    }

    const deletedProject = await ProjectModel.delete(id);

    if (req.user && req.user.id) {
      await AuditLogModel.logAction(req.user.id, 'DELETE', 'projects', id, { title: deletedProject.title });
    }

    return res.status(200).json({ message: 'Investigación eliminada exitosamente.' });
  } catch (error) {
    console.error(`[ERROR] Controller failed to delete project ID ${id}:`, error);
    return res.status(500).json({ message: 'Error interno al eliminar la investigación.' });
  }
};

/**
 * Retrieves projects for the Admin panel with Data Isolation logic.
 *
 * @param {Object} req - The HTTP request object containing req.user.
 * @param {Object} res - The HTTP response object.
 * @returns {Promise<Object>} JSON array of filtered projects based on role.
 * @throws {Error} Catches internal database errors and returns a 500 status.
 */
const getPanelProjects = async (req, res) => {
  try {
    const { role, id } = req.user; 
    let projectsList;

    if (role === 'admin') {
      projectsList = await ProjectModel.getAll();
    } else {
      projectsList = await ProjectModel.getByAuthorId(id);
    }

    return res.status(200).json(projectsList);
  } catch (error) {
    console.error('[ERROR] Controller failed to fetch panel projects:', error);
    return res.status(500).json({ message: 'Error interno al cargar el panel.' });
  }
};

/**
 * Serves the binary image file for a specific project.
 *
 * @param {Object} req - The HTTP request object.
 * @param {Object} res - The HTTP response object.
 * @returns {Object} The binary image stream or an error message.
 */
const getProjectImage = async (req, res) => {
  const { id } = req.params;
  try {
    const project = await ProjectModel.getImage(id);
    
    if (!project || !project.image_data) {
      return res.status(404).json({ message: 'Imagen no encontrada.' });
    }

    res.set('Content-Type', project.image_mimetype);
    res.set('Cross-Origin-Resource-Policy', 'cross-origin');
    return res.send(project.image_data);
  } catch (error) {
    console.error(`[ERROR] Controller failed to serve image for project ${id}:`, error);
    return res.status(500).json({ message: 'Error interno al obtener la imagen.' });
  }
};

/**
 * Serves the binary PDF file for a specific project.
 *
 * @param {Object} req - The HTTP request object.
 * @param {Object} res - The HTTP response object.
 * @returns {Object} The binary PDF stream or an error message.
 */
const getProjectPdf = async (req, res) => {
  const { id } = req.params;
  try {
    const project = await ProjectModel.getPdf(id);
    
    if (!project || !project.pdf_data) {
      return res.status(404).json({ message: 'Documento PDF no encontrado.' });
    }

    res.set('Content-Type', project.pdf_mimetype);
    res.set('Content-Disposition', 'inline; filename="investigacion.pdf"'); 
    return res.send(project.pdf_data);
  } catch (error) {
    console.error(`[ERROR] Controller failed to serve PDF for project ${id}:`, error);
    return res.status(500).json({ message: 'Error interno al obtener el documento.' });
  }
};


module.exports = { 
  getAllProjects, getProjectById, createProject, updateProject, 
  deleteProject, getPanelProjects, 
  getProjectImage, getProjectPdf
};